/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//some sram calculation
#define SRAM_START			0x20000000
#define SRAM_SIZE			((1024)*(128))
#define TASK_SIZE			1024U
#define SRAM_END    		((SRAM_START)+SRAM_SIZE )

#define TASK1_START			SRAM_END
#define TASk2_START			((SRAM_END) - (1*TASK_SIZE))
#define TASk3_START			((SRAM_END) - (2*TASK_SIZE))
#define TASk4_START			((SRAM_END) - (3*TASK_SIZE))
#define TASk_SCHEDULER		((SRAM_END) - (4*TASK_SIZE))

#define HSI_CLOCK			16000000U
#define SYSTICK_CLK			HSI_CLOCK
uint32_t tick_s	 =			1000;
uint32_t *psrvr  = 			(uint32_t*)0xE000E014;
uint32_t *pscsr  = 			(uint32_t*)0xE000E010;


void task_1(void);
void task_2(void);
void task_3(void);
void task_4(void);
void task_scheduler(void);

void init_systick_timer(uint32_t tick);


int main(void)
{

	init_systick_timer(tick_s);
    /* Loop forever */
	for(;;);
}

void task_1(void)
{
	while(1)
	{
		printf("Running task_1");
	}

}

void task_2(void)
{
	while(1)
	{
		printf("Running task_2");
	}

}

void task_3(void)
{
	while(1)
	{
		printf("Running task_3");
	}

}

void task_4(void)
{
	while(1)
	{
		printf("Running task_4");
	}

}

void task_scheduler(void)
{

}

void init_systick_timer(uint32_t tick)
{

	uint32_t count_value = ((SYSTICK_CLK)/(tick))-1;
	//Clear the value of reload register upto 24 bits
	*psrvr 	&= ~(0x00FFFFFF);

	//set the count value in reload register
	*psrvr |= count_value;

	*pscsr |= 1<<0; // Enables the counter
	*pscsr |= 1<<1; // Enables SysTick exception request
	*pscsr |= 1<<2; // Set the processor clock

}


